/**
 ******************************************************************************
 * @file    Peer.java
 * @author  Leonardo Winter Pereira
 * @author  Luis Felipe Mazzuchetti Ortiz
 * @version v1.0
 * @date    16 de ago de 2018
 * @brief	File responsible to declare and define the Peer class
 ******************************************************************************
 */

package Database;

/**
 * @name    Peer
 * @brief	This class is responsible to define what is a Peer 
 * 			in this project.
 * 			It is a really basic class with only some methods.
 */
public class Peer 
{
    /**
     * @name    id
     * @brief	An 4 bytes integer value representing the unique ID
     * 			of the peer.
     * 			4 bytes were used to represent a real world approach.
     */
    private int id;
    
    /**
     * @name    publicKeyByte
     * @brief	Array of bytes representing the public key of the peer.
     * 			This public key is generated by the Crypto Class and every
     * 			time a peer is allocated, a new value for this field is generated.
     */
    private byte[] publicKeyByte;

    /**
     * @name    resourceList
     * @brief	List of resources available for each peer.
     */
    private ResourceList resourceList;

    /**
     * @name    statusResponse
     * @brief	The peer current response status
     */
    private boolean statusResponse;

    /**
     * @name    Peer
     * @brief	The class constructor.
     * 			Only configures the default values for
     * 			the peer in question.
     * @param	_id				: the peer unique ID
     * @param	_publicKeyByte	: the peer public key
     * @param	_qtyResources	: the number of available resources
     */
    public Peer(int		_id, 
    			byte[] 	_publicKeyByte,
                int     _qtyResources) 
    {
        this.id = _id;
        
        this.publicKeyByte = _publicKeyByte;
        
        this.resourceList = new ResourceList(_qtyResources);

        this.statusResponse = false;
        
        return;
    }

    /**
     * @name    getId
     * @brief   returns the peer unique ID
     * @return	integer value containing the peer unique ID
     */
    public int getId() 
    {
    	return this.id;
	}  

    /**
     * @name    getPublicKeyByte
     * @brief   Returns the peer public key previously stored
     * @return	a byte array containing the peer public key
     */
    public byte[] getPublicKeyByte()
    {
    	return publicKeyByte;
    }

    /**
     * @name    getResourceList
     * @brief   Returns the peer resource list
     * @return	A ResourceList containing the resource list
     */
    public ResourceList getResourceList()
    {
        return this.resourceList;
    }

    /**
     * @name    getStatusResponse
     * @brief   Default getter for statusResponse member
     * @return	boolean value
     */
    public boolean getStatusResponse() 
    {
        return this.statusResponse;
    }

    /**
     * @name    setStatusResponse
     * @brief   Default setter for the statusResponse member
     * @param	_statusResponse	: whether or not the flag must be setted
     */
    public void setStatusResponse(boolean _statusResponse) 
    {
        this.statusResponse = _statusResponse;

        return;
    }  
}
