
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TravelAgencyService", targetNamespace = "http://tas.sd.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TravelAgencyService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerHotelInterest", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterest")
    @ResponseWrapper(localName = "registerHotelInterestResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterestResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerHotelInterestRequest", output = "http://tas.sd.br/TravelAgencyService/registerHotelInterestResponse")
    public void registerHotelInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        Accommodation arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://tas.sd.br/", className = "client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://tas.sd.br/", className = "client.HelloResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/helloRequest", output = "http://tas.sd.br/TravelAgencyService/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns client.FlightTicketManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPassages", targetNamespace = "http://tas.sd.br/", className = "client.SearchPassages")
    @ResponseWrapper(localName = "searchPassagesResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchPassagesResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchPassagesRequest", output = "http://tas.sd.br/TravelAgencyService/searchPassagesResponse")
    public FlightTicketManager searchPassages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Date arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerPassageInterest", targetNamespace = "http://tas.sd.br/", className = "client.RegisterPassageInterest")
    @ResponseWrapper(localName = "registerPassageInterestResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterPassageInterestResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerPassageInterestRequest", output = "http://tas.sd.br/TravelAgencyService/registerPassageInterestResponse")
    public void registerPassageInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        FlightTicket arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        FlightTicket arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.AccommodationManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchHotelByCity", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByCity")
    @ResponseWrapper(localName = "searchHotelByCityResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByCityResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchHotelByCityRequest", output = "http://tas.sd.br/TravelAgencyService/searchHotelByCityResponse")
    public AccommodationManager searchHotelByCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.AccommodationManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchHotelByName", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByName")
    @ResponseWrapper(localName = "searchHotelByNameResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByNameResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchHotelByNameRequest", output = "http://tas.sd.br/TravelAgencyService/searchHotelByNameResponse")
    public AccommodationManager searchHotelByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveHotel", targetNamespace = "http://tas.sd.br/", className = "client.ReserveHotel")
    @ResponseWrapper(localName = "reserveHotelResponse", targetNamespace = "http://tas.sd.br/", className = "client.ReserveHotelResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/reserveHotelRequest", output = "http://tas.sd.br/TravelAgencyService/reserveHotelResponse")
    public boolean reserveHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Accommodation arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyPassage", targetNamespace = "http://tas.sd.br/", className = "client.BuyPassage")
    @ResponseWrapper(localName = "buyPassageResponse", targetNamespace = "http://tas.sd.br/", className = "client.BuyPassageResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/buyPassageRequest", output = "http://tas.sd.br/TravelAgencyService/buyPassageResponse")
    public boolean buyPassage(
        @WebParam(name = "arg0", targetNamespace = "")
        FlightTicket arg0);

    /**
     * 
     * @return
     *     returns java.util.List<client.FlightTicketInterest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketInterestList", targetNamespace = "http://tas.sd.br/", className = "client.GetTicketInterestList")
    @ResponseWrapper(localName = "getTicketInterestListResponse", targetNamespace = "http://tas.sd.br/", className = "client.GetTicketInterestListResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/getTicketInterestListRequest", output = "http://tas.sd.br/TravelAgencyService/getTicketInterestListResponse")
    public List<FlightTicketInterest> getTicketInterestList();

    /**
     * 
     * @return
     *     returns java.util.List<client.AccommodationInterest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccommodationInterestList", targetNamespace = "http://tas.sd.br/", className = "client.GetAccommodationInterestList")
    @ResponseWrapper(localName = "getAccommodationInterestListResponse", targetNamespace = "http://tas.sd.br/", className = "client.GetAccommodationInterestListResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/getAccommodationInterestListRequest", output = "http://tas.sd.br/TravelAgencyService/getAccommodationInterestListResponse")
    public List<AccommodationInterest> getAccommodationInterestList();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifyTicketsInterests", targetNamespace = "http://tas.sd.br/", className = "client.NotifyTicketsInterests")
    @ResponseWrapper(localName = "notifyTicketsInterestsResponse", targetNamespace = "http://tas.sd.br/", className = "client.NotifyTicketsInterestsResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/notifyTicketsInterestsRequest", output = "http://tas.sd.br/TravelAgencyService/notifyTicketsInterestsResponse")
    public void notifyTicketsInterests(
        @WebParam(name = "arg0", targetNamespace = "")
        FlightTicket arg0);

}
