
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TravelAgencyService", targetNamespace = "http://tas.sd.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TravelAgencyService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertHotelEntry", targetNamespace = "http://tas.sd.br/", className = "client.InsertHotelEntry")
    @ResponseWrapper(localName = "insertHotelEntryResponse", targetNamespace = "http://tas.sd.br/", className = "client.InsertHotelEntryResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/insertHotelEntryRequest", output = "http://tas.sd.br/TravelAgencyService/insertHotelEntryResponse")
    public boolean insertHotelEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        float arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyPassage", targetNamespace = "http://tas.sd.br/", className = "client.BuyPassage")
    @ResponseWrapper(localName = "buyPassageResponse", targetNamespace = "http://tas.sd.br/", className = "client.BuyPassageResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/buyPassageRequest", output = "http://tas.sd.br/TravelAgencyService/buyPassageResponse")
    public boolean buyPassage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        float arg6);

    /**
     * 
     * @return
     *     returns client.FlightTicketManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadDBPassages", targetNamespace = "http://tas.sd.br/", className = "client.LoadDBPassages")
    @ResponseWrapper(localName = "loadDBPassagesResponse", targetNamespace = "http://tas.sd.br/", className = "client.LoadDBPassagesResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/loadDBPassagesRequest", output = "http://tas.sd.br/TravelAgencyService/loadDBPassagesResponse")
    public FlightTicketManager loadDBPassages();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns client.FlightTicketManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPassages", targetNamespace = "http://tas.sd.br/", className = "client.SearchPassages")
    @ResponseWrapper(localName = "searchPassagesResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchPassagesResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchPassagesRequest", output = "http://tas.sd.br/TravelAgencyService/searchPassagesResponse")
    public FlightTicketManager searchPassages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @return
     *     returns client.AccommodationManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadDBHotels", targetNamespace = "http://tas.sd.br/", className = "client.LoadDBHotels")
    @ResponseWrapper(localName = "loadDBHotelsResponse", targetNamespace = "http://tas.sd.br/", className = "client.LoadDBHotelsResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/loadDBHotelsRequest", output = "http://tas.sd.br/TravelAgencyService/loadDBHotelsResponse")
    public AccommodationManager loadDBHotels();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveHotel", targetNamespace = "http://tas.sd.br/", className = "client.ReserveHotel")
    @ResponseWrapper(localName = "reserveHotelResponse", targetNamespace = "http://tas.sd.br/", className = "client.ReserveHotelResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/reserveHotelRequest", output = "http://tas.sd.br/TravelAgencyService/reserveHotelResponse")
    public boolean reserveHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.AccommodationManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchHotelByName", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByName")
    @ResponseWrapper(localName = "searchHotelByNameResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByNameResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchHotelByNameRequest", output = "http://tas.sd.br/TravelAgencyService/searchHotelByNameResponse")
    public AccommodationManager searchHotelByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerPassageInterest", targetNamespace = "http://tas.sd.br/", className = "client.RegisterPassageInterest")
    @ResponseWrapper(localName = "registerPassageInterestResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterPassageInterestResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerPassageInterestRequest", output = "http://tas.sd.br/TravelAgencyService/registerPassageInterestResponse")
    public String registerPassageInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        float arg10);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "registerPackageInterest", targetNamespace = "http://tas.sd.br/", className = "client.RegisterPackageInterest")
    @ResponseWrapper(localName = "registerPackageInterestResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterPackageInterestResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerPackageInterestRequest", output = "http://tas.sd.br/TravelAgencyService/registerPackageInterestResponse")
    public void registerPackageInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        float arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        int arg11);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPassageEntry", targetNamespace = "http://tas.sd.br/", className = "client.InsertPassageEntry")
    @ResponseWrapper(localName = "insertPassageEntryResponse", targetNamespace = "http://tas.sd.br/", className = "client.InsertPassageEntryResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/insertPassageEntryRequest", output = "http://tas.sd.br/TravelAgencyService/insertPassageEntryResponse")
    public boolean insertPassageEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        float arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerHotelInterestByCity", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterestByCity")
    @ResponseWrapper(localName = "registerHotelInterestByCityResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterestByCityResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerHotelInterestByCityRequest", output = "http://tas.sd.br/TravelAgencyService/registerHotelInterestByCityResponse")
    public String registerHotelInterestByCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerHotelInterestByHotel", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterestByHotel")
    @ResponseWrapper(localName = "registerHotelInterestByHotelResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterestByHotelResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerHotelInterestByHotelRequest", output = "http://tas.sd.br/TravelAgencyService/registerHotelInterestByHotelResponse")
    public String registerHotelInterestByHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3);

    /**
     * 
     * @return
     *     returns java.util.List<client.FlightTicketInterest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketInterestList", targetNamespace = "http://tas.sd.br/", className = "client.GetTicketInterestList")
    @ResponseWrapper(localName = "getTicketInterestListResponse", targetNamespace = "http://tas.sd.br/", className = "client.GetTicketInterestListResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/getTicketInterestListRequest", output = "http://tas.sd.br/TravelAgencyService/getTicketInterestListResponse")
    public List<FlightTicketInterest> getTicketInterestList();

    /**
     * 
     * @return
     *     returns java.util.List<client.AccommodationInterest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccommodationInterestList", targetNamespace = "http://tas.sd.br/", className = "client.GetAccommodationInterestList")
    @ResponseWrapper(localName = "getAccommodationInterestListResponse", targetNamespace = "http://tas.sd.br/", className = "client.GetAccommodationInterestListResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/getAccommodationInterestListRequest", output = "http://tas.sd.br/TravelAgencyService/getAccommodationInterestListResponse")
    public List<AccommodationInterest> getAccommodationInterestList();

    /**
     * 
     * @return
     *     returns java.util.List<client.PackageInterest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPackageInterestList", targetNamespace = "http://tas.sd.br/", className = "client.GetPackageInterestList")
    @ResponseWrapper(localName = "getPackageInterestListResponse", targetNamespace = "http://tas.sd.br/", className = "client.GetPackageInterestListResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/getPackageInterestListRequest", output = "http://tas.sd.br/TravelAgencyService/getPackageInterestListResponse")
    public List<PackageInterest> getPackageInterestList();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerHotelInterest", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterest")
    @ResponseWrapper(localName = "registerHotelInterestResponse", targetNamespace = "http://tas.sd.br/", className = "client.RegisterHotelInterestResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/registerHotelInterestRequest", output = "http://tas.sd.br/TravelAgencyService/registerHotelInterestResponse")
    public void registerHotelInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        float arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.AccommodationManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchHotelByCity", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByCity")
    @ResponseWrapper(localName = "searchHotelByCityResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchHotelByCityResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchHotelByCityRequest", output = "http://tas.sd.br/TravelAgencyService/searchHotelByCityResponse")
    public AccommodationManager searchHotelByCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyPackage", targetNamespace = "http://tas.sd.br/", className = "client.BuyPackage")
    @ResponseWrapper(localName = "buyPackageResponse", targetNamespace = "http://tas.sd.br/", className = "client.BuyPackageResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/buyPackageRequest", output = "http://tas.sd.br/TravelAgencyService/buyPackageResponse")
    public int buyPackage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        float arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        float arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        float arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        int arg13);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg8
     * @return
     *     returns java.util.List<client.Packages>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPackages", targetNamespace = "http://tas.sd.br/", className = "client.SearchPackages")
    @ResponseWrapper(localName = "searchPackagesResponse", targetNamespace = "http://tas.sd.br/", className = "client.SearchPackagesResponse")
    @Action(input = "http://tas.sd.br/TravelAgencyService/searchPackagesRequest", output = "http://tas.sd.br/TravelAgencyService/searchPackagesResponse")
    public List<Packages> searchPackages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8);

}
